enum ActionKind {
    Walking,
    Idle,
    Jumping,
    Atack,
    shine
}
namespace SpriteKind {
    export const NextL = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.NextL, function (sprite, otherSprite) {
    Nivel += 1
    Animations()
    Shark.x = 35
    Shark.ax = 7
    info.setLife(2)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (Shark.vy == 0) {
    	
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    music.beamUp.play()
    info.changeLifeBy(1)
    otherSprite.destroy()
})
function Animations () {
    Shark.ax = 7
    if (Nivel == 0) {
        tiles.setTilemap(tilemap`level0`)
    } else if (Nivel == 1) {
        tiles.setTilemap(tilemap`level4`)
    } else if (Nivel == 2) {
        tiles.setTilemap(tilemap`level7`)
    } else {
        game.over(true)
    }
    for (let value of sprites.allOfKind(SpriteKind.Food)) {
        value.destroy()
    }
    for (let value of sprites.allOfKind(SpriteKind.Enemy)) {
        value.destroy()
    }
    Breath = animation.createAnimation(ActionKind.Idle, 500)
    Upper = animation.createAnimation(ActionKind.Walking, 100)
    Attack = animation.createAnimation(ActionKind.Atack, 50)
    shine = animation.createAnimation(ActionKind.shine, 200)
    shine.addAnimationFrame(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . b . . . . . . . 
        . . . . . . . b d b . . . . . . 
        . . . . . . b 5 5 5 b . . . . . 
        . . . . . b b 5 5 5 b b . . . . 
        . . b b b b 5 5 5 1 1 b b b b . 
        . . b 5 5 5 5 5 5 1 1 5 5 5 b . 
        . . b d d 5 5 5 5 5 5 5 d d b . 
        . . . b d d 5 5 5 5 5 d d b . . 
        . . . c b 5 5 5 5 5 5 5 b c . . 
        . . . c b 5 5 5 5 5 5 5 b c . . 
        . . . c 5 5 d d b d d 5 5 c . . 
        . . . c 5 d d c c c d d 5 c . . 
        . . . c c c c . . . c c c c . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `)
    shine.addAnimationFrame(img`
        . . . . . . . b b . . . . . . . 
        . . . . . . b d d b . . . . . . 
        . . . . . b d 5 5 d b . . . . . 
        . . . . b b 5 5 5 5 b b . . . . 
        . . . . b 5 5 5 5 5 5 b . . . . 
        b b b b b 5 5 5 5 1 1 d b b b b 
        b 5 5 5 5 5 5 5 5 1 1 1 5 5 5 b 
        b d d 5 5 5 5 5 5 1 1 1 5 d d b 
        . b d d 5 5 5 5 5 5 5 5 d d b . 
        . . b b 5 5 5 5 5 5 5 5 b b . . 
        . . c b 5 5 5 5 5 5 5 5 b c . . 
        . . c 5 5 5 5 d d 5 5 5 5 c . . 
        . . c 5 5 d b b b b d 5 5 c . . 
        . . c 5 d b c c c c b d 5 c . . 
        . . c c c c . . . . c c c c . . 
        . . . . . . . . . . . . . . . . 
        `)
    shine.addAnimationFrame(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . b b . . . . . . . 
        . . . . . . b 5 5 b . . . . . . 
        . . . b b b 5 5 1 1 b b b . . . 
        . . . b 5 5 5 5 1 1 5 5 b . . . 
        . . . . b d 5 5 5 5 d b . . . . 
        . . . . c b 5 5 5 5 b c . . . . 
        . . . . c 5 d d d d 5 c . . . . 
        . . . . c 5 d c c d 5 c . . . . 
        . . . . c c c . . c c c . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `)
    shine.addAnimationFrame(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . b . . . . . . . 
        . . . . . . . b d b . . . . . . 
        . . . . . . . c d c . . . . . . 
        . . . . . . . c 5 c . . . . . . 
        . . . . . . c d 5 d c . . . . . 
        . . . b c c d 5 5 5 d c c b . . 
        . . b d d 5 5 5 5 5 5 5 d d b . 
        . . . b c c d 5 5 5 d c c b . . 
        . . . . . . c d 5 d c . . . . . 
        . . . . . . . c 5 c . . . . . . 
        . . . . . . . c d c . . . . . . 
        . . . . . . . b d b . . . . . . 
        . . . . . . . . b . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `)
    Breath.addAnimationFrame(img`
        ..............fffcc.............
        ..............fbbddc............
        ...............fbbddc...........
        ccc............fcbbccf..........
        cbbcc.........ffccccccffffff....
        .cbbdc.....fffcbbbbbbbbbbbbbff..
        .fbbddc..ffcccbbbbcbcbbbbbbbbbff
        ..fbbdfffcccccbbbcbcbbdfbbbbbcbf
        ..fcbbbcccccccbbbcbcb1ff1111bbbf
        ..fccbcccccccccbbbbbb11111111bf.
        .fcbbfffccccccccbbbb11cc33cccf..
        .fbbf...cbdbcccccbbb111c131cf...
        fbbf.....ccdddddfbbbc111cfff....
        fff........ccddfbbdbffffff......
        ..............fbbdbf............
        ..............fffff.............
        `)
    Breath.addAnimationFrame(img`
        ....................................
        ....................................
        ....................................
        ...............ffffcc...............
        ...............fbbbddc..............
        ................fbbbddcffffff.......
        ccccc.......fffcbbbbbbbbbbbbbff.....
        cbbbdc....ffcccbbbbbcbcbbbbbbbbff...
        .cbbddcfffcccccbbbbcbbcbbbbbbbbbff..
        ..fbbdbccccccccbbbbcbcbbdfbbbbbbcf..
        ..fcbbcccccbccccbbbbbcbbffbbbbbbbf..
        ..fccbffcbcccccccbbbbcbb1111111bf...
        .fcbbf..ccbbbccccccbbbb11333111f....
        fbbff.....cccbddfbbbdb11b1b1f.......
        fff..........ccfbbbdbfcccccf........
        ...............ffffff...............
        `)
    Upper.addAnimationFrame(img`
        ...........fffcc.......b.d..........
        ...........fbbbbcffffbccccb.........
        ............fbfffbbbbbbbbbc.........
        ............ffbbbbdfb111bbc.........
        ..........ffcbbbbbff11111bf.........
        .........fcccbcbcbb11cccc1f.........
        ccccc...fcccbcbcbbb1c1c1cf..........
        cbbddccfccccbcbcbbb1133c............
        .ccbddbcccccbbbbbbb1c3d1c...........
        ..ccbbcccccccbbbbb11c11c............
        ..fccbffccccccbbbb111cf.............
        ..fccf.cbbcccccbbbc11c..............
        .fcbbf...bcccdfbbbc1c...............
        .fbbf.......dfbbdbff................
        fbbf........fbbdbf..................
        fff.........fffff...................
        `)
    Upper.addAnimationFrame(img`
        ...........fffcc....................
        ...........fbbbbcfffffffff..........
        ............fbfffbbbbbbbbbf.........
        ............ffbbbbdfb111bbf.........
        ..........ffcbbbbbff11111bf.........
        .........fcccbcbcbb11cccc1f.........
        ccccc...fcccbcbcbbb1c1c1cf..........
        cbbddccfccccbcbcbbb1133c............
        .ccbddbcccccbbbbbbb1c331c...........
        ..ccbbcccccccbbbbb11cb11f...........
        ..fccbffccccccbbbb111cfc............
        ..fccf.cbbcccccbbbc11c..............
        .fcbbf...ccdddfbbbc1cf..............
        .fbbf.......dfbbdbff................
        fbbf........fbbdbf..................
        fff.........fffff...................
        `)
    Attack.addAnimationFrame(img`
        ...........fffcc...fffffff..........
        ...........fbbbbcffbbbbbbbf.........
        ............fbffbbbbb111bbf.........
        ............ffbbbbff11111bf.........
        ..........ffcbbbbbff1cccc1f.........
        .........fcccbcbcbb11c1c1cf.........
        .ccccc..fcccbcbcbbb113131cf.........
        .cbbddcfccccbcbcbbb11c333c..........
        ..ccbddcccccbbbbbbb11c333c..........
        ...ccbbccccccbbbbb111c133c..........
        ...fccbfccccccbbbb111c131cc.........
        ...fccfcbbcdddcbbbc111c31cc.........
        ..fcbbf...cdddfbbbc111111c..........
        ..fbbf......dfbbdbf1111cc...........
        .fbbf.......fbbdbfffccc.............
        .fff........fffff...................
        `)
    Attack.addAnimationFrame(img`
        ...........fffcc...fffffff..........
        ...........fbbbbcffbbbbbbbf.........
        ............fbffbbbbb111bbf.ff......
        ............ffbbbbff11111bf..f......
        ..........ffcbbbbbff1cccc1f..ff.....
        .........fcccbcbcbb11c1c1cf...f.....
        .ccccc..fcccbcbcbbb113131cf...f.....
        .cbbddcfccccbcbcbbb11c333c....f.....
        ..ccbddcccccbbbbbbb11c333c....f.....
        ...ccbbccccccbbbbb111c133c....f.....
        ...fccbfccccccbbbb111c131cc...f.....
        ...fccfcbbcccccbbbc111c31cc..ff.....
        ..fcbbf.cdddddfbbbc111111c...f......
        ..fbbf...cdddfbbdbf1111cc...ff......
        .fbbf.....ccfbbdbfffccc.....f.......
        .fff........fffff...................
        `)
    Attack.addAnimationFrame(img`
        ...........fffcc...fffffff..........
        ...........fbbbbcffbbbbbbbf.........
        ............fbffbbbbb111bbf.ff......
        ............ffbbbbff11cccbf..f..ff..
        ..........ffcbbbbbff1c1c1cf..ff..f..
        .........fcccbcbcbb11c131cf...f..f..
        .ccccc..fcccbcbcbbb113131cf...f..f..
        .cbbddcfccccbcbcbbb11c333c....f..f..
        ..ccbddcccccbbbbbbb11c333c....f..f..
        ...ccbbccccccbbbbb111c133c....f..f..
        ...fccbfccccccbbbb111c131cc...f..f..
        ...fccfcbbcccccbbbc111c11cc..ff..f..
        ..fcbbf.cdddddfbbbc111111c...f..f...
        ..fbbf...cdddfbbdbf1111cc...ff......
        .fbbf.....ccfbbdbfffccc.....f.......
        .fff........fffff...................
        `)
    Attack.addAnimationFrame(img`
        ...........fffcc...fffffff.......222
        ...........fbbbbcffbbbbbbbf.......22
        ............fbffbbbbb111bbf.ff.....2
        ............ffbbbbff11111bf..f..ff.2
        ..........ffcbbbbbff1cccc1f..ff..f.2
        .........fcccbcbcbb1c1c1cff...f..f.2
        .ccccc..fcccbcbcbbb1333ccf....f..f..
        .cbbddcfccccbcbcbbb1c333c.....f..f..
        ..ccbddcccccbbbbbbb1c333c.....f..f.2
        ...ccbbccccccbbbbb11c333c.....f..f.2
        ...fccbfccccccbbbb11c133cc....f..f..
        ...fccfcbbcccccbbbc11c31cc...ff..f..
        ..fcbbf.cdddddfbbbc111111c...f..f..2
        ..fbbf...cdddfbbdbf1111cc...ff......
        .fbbf.....ccfbbdbfffccc.....f.......
        .fff........fffff...................
        `)
    animation.attachAnimation(Shark, Breath)
    animation.attachAnimation(Shark, Upper)
    animation.attachAnimation(Shark, Attack)
    animation.attachAnimation(Next, shine)
    animation.setAction(Next, ActionKind.shine)
    for (let value of tiles.getTilesByType(assets.tile`myTile22`)) {
        Enemigo = sprites.create(assets.image`fish`, SpriteKind.Enemy)
        animation.runImageAnimation(
        Enemigo,
        [img`
            ...........................ccc..
            ..........................cc....
            .......................1cccb....
            ...............cccacccccadddd...
            ....baccac1ddaccbbbbbdccccacc...
            ....c1bbbbcaccbbbdacccabbbbbb...
            ....cbfbbbc4bbccaccbbbbbdcaccc..
            ....abbbbbc6cccbbbbcccccacbbb...
            ....cbfbbba4ddccacccbbbbbbbdd...
            ....cbbbbbcccccbbbbbdddddddbd...
            ....caccaccdcbcacccacccccacbb...
            .............acbbbbbbbbbbbccc...
            ............................c...
            ................................
            ................................
            ................................
            `,img`
            .........................ddccc..
            ........................ddcc.b..
            ..............bbbbdddddddccb.b..
            .......ddcd.dd.cccacccccadddd...
            ....baccac1ddaccbbbbbdccccacc...
            ....c1bbbbcaccbbbdacccabbbbbb...
            ....cbfbbbc4bbccaccbbbbbdcaccc..
            ....abbbbbc6cccbbbbcccccacbbbb..
            ....cbfbbba4ddccacccbbbbbbbdd...
            ....cbbbbbcccccbbbbbdddddddbd...
            ....caccaccdcbcacccacccccacbbb..
            .......dddd..acbbbbddddddbcccb..
            ......................d..dd.cb..
            ................................
            ................................
            ................................
            `,img`
            ............................cccd
            .........................d.ccddd
            ..................bbbbbbdcccddc.
            ......dbbbc.....cccacccccadddcc.
            .....baccacdbbaccbbbdddcccccccc.
            ....bc11bbbcaccbdddaccccddddddd.
            ....bc1fbbbc4bdccaccdddddccaacc.
            ....babbbbbcaccccdddccccacbbbdb.
            ....bcbfbbba4dbccacccbbbbdddddc.
            ....bcbbbbbcccccbddddddddddbcc..
            ....bcaccaacdcdcacccacccccacc...
            ......bbbbbb..acdbbbbbddcbbccc..
            ....................dddddddbcc..
            ............................bcc.
            ................................
            ................................
            `],
        200,
        true
        )
        tiles.placeOnTile(Enemigo, value)
        tiles.setTileAt(value, assets.tile`transparency16`)
    }
    for (let value of tiles.getTilesByType(assets.tile`myTile26`)) {
        Fish = sprites.create(assets.image`fish`, SpriteKind.Food)
        animation.runImageAnimation(
        Fish,
        [img`
            ................................
            ................................
            ...........4444444444.......44..
            ........44445d45d5d54444....44..
            ......4445d5dd4ddd4ddd5444..45..
            ....44dddd4dd545d54d54ddd44445..
            ..444d45dd45cb4dd545c45d4dd44d..
            ..4ddf4dd54bb54d5c4bb4d545dd4d..
            ..444444444444444444444444444d..
            ...4d5dd5d45dd4d5d4d54d54bdd4d..
            ...4444444ddd5dddd5dd5dd444445..
            .........4444444444444444...44..
            ................................
            ................................
            ................................
            ................................
            `,img`
            ................................
            ................................
            ..........44444444444444........
            ........444d5d45d5d5ddd4.....44.
            ......4445d5dd4ddd4ddd5d44..455.
            ....44dddd4dd545d54d54ddd44445..
            ..44dd45dd45cb4dd545c45d4dd44d..
            ..4ddf4dd54bb54d5c4bb4d545dd4d..
            ..444444444444444444444444444d..
            ...4d5dd5d45dd4d5d4d54d54bdd4d..
            ...4444dddddd5dddd5ddd5d444445..
            .......44d5ddd5d5ddd5dd44...44..
            ........444444444444444......4..
            ................................
            ................................
            ................................
            `],
        200,
        true
        )
        tiles.placeOnTile(Fish, value)
        tiles.setTileAt(value, assets.tile`transparency16`)
    }
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    music.smallCrash.play()
    if (controller.A.isPressed()) {
        otherSprite.destroy()
    } else {
        info.changeLifeBy(-1)
        otherSprite.destroy()
    }
})
let Fish: Sprite = null
let Enemigo: Sprite = null
let shine: animation.Animation = null
let Attack: animation.Animation = null
let Upper: animation.Animation = null
let Breath: animation.Animation = null
let Nivel = 0
let Next: Sprite = null
let Shark: Sprite = null
Shark = sprites.create(img`
    ..............fffcc.............
    ..............fcbddcc...........
    ...............fbbddcc..........
    ...............fcbbccf..........
    ..ccc.........ffccccccfffff.....
    ..cbbcc....fffcbbbbcbbbbbbbff...
    ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
    ...fbbdcfcccccbbbcbcbbffbbbbbbff
    ....fbbffcccccbbbbbcb1ff11bbbcbf
    ....fcbbcccccccbbbbb11111111bbbf
    ....fcccccccccccbbbb11cc33111bf.
    ...fcbbffbdbcccccbbb111c13cccf..
    ...fbbf..ccddddcfbbbc111c31cf...
    ..fbbf.....ccdccbbdbf111cccf....
    ..fff........ccbbdcfcccc........
    ..............fffff.............
    `, SpriteKind.Player)
Next = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . b . . . . . . . 
    . . . . . . . b d b . . . . . . 
    . . . . . . b 5 5 5 b . . . . . 
    . . . . . b b 5 5 5 b b . . . . 
    . . b b b b 5 5 5 1 1 b b b b . 
    . . b 5 5 5 5 5 5 1 1 5 5 5 b . 
    . . b d d 5 5 5 5 5 5 5 d d b . 
    . . . b d d 5 5 5 5 5 d d b . . 
    . . . c b 5 5 5 5 5 5 5 b c . . 
    . . . c b 5 5 5 5 5 5 5 b c . . 
    . . . c 5 5 d d b d d 5 5 c . . 
    . . . c 5 d d c c c d d 5 c . . 
    . . . c c c c . . . c c c c . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.NextL)
Next.x = 950
Next.y = 215
Shark.ay = 800
Shark.y = 220
Shark.x = 35
controller.moveSprite(Shark, 0, 150)
scene.cameraFollowSprite(Shark)
info.setLife(2)
scene.setBackgroundColor(9)
Nivel = 0
Animations()
game.onUpdate(function () {
    if (Shark.vy < 0) {
        animation.setAction(Shark, ActionKind.Walking)
    } else if (controller.A.isPressed()) {
        animation.stopAnimation(animation.AnimationTypes.All, Shark)
        animation.setAction(Shark, ActionKind.Atack)
    } else {
        animation.setAction(Shark, ActionKind.Idle)
    }
})
forever(function () {
    if (Nivel <= 1) {
        music.playMelody("G F G F E F A B ", 125)
    } else {
        music.playMelody("C5 B C5 A C5 B A G ", 135)
    }
})
